version: '3'
networks:
  backbone:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
  proxy:
        ipam:
            driver: default
            config:
                - subnet: 172.29.0.0/16
  paperless:

services:

 collabora:
    image: collabora/code
    container_name: collabora
    restart: always
    ports:
      - 127.0.0.1:9980:9980
    cap_add:
      - MKNOD
    environment:
      - domain=${DOMAIN}
      - username=${COLLABORA_USER}
      - password=${COLLABORA_PASSWORD}
      - ssl.enable=false
      - ssl.termination=true
    networks:
      - backbone

 reverseproxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: reverseproxy-manager
    restart: always
    networks:
        backbone:
            ipv4_address: 172.28.1.1
        proxy:
            ipv4_address: 172.29.1.1
        paperless:
    ports:
        - '80:80'
        - '81:81'
        - '443:443'
    volumes:
        - revproxdata:/data
        - revproxletsencrypt:/etc/letsencrypt

  # proxy manager volumes
  revproxdata:
  revproxletsencrypt:
