name: Validate Docker Compose

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  validate-docker-compose:
    runs-on: ubuntu-latest
    env:
      LDAP_LOG_LEVEL: 256
      LDAP_ORGANISATION: Max_Homelab
      LDAP_DOMAIN: yourlocalcloud.de
      LDAP_BASE_DN: " "
      LDAP_ADMIN_PASSWORD: secret
      LDAP_CONFIG_PASSWORD: secret
      LDAP_READONLY_USER: false
      LDAP_RFC2307BIS_SCHEMA: false
      LDAP_BACKEND: mdb
      LDAP_TLS: true
      LDAP_TLS_CRT_FILENAME: ldap.crt
      LDAP_TLS_KEY_FILENAME: ldap.key
      LDAP_TLS_DH_PARAM_FILENAME: dhparam.pem
      LDAP_TLS_CA_CRT_FILENAME: ca.crt
      LDAP_TLS_ENFORCE: false
      LDAP_TLS_CIPHER_SUITE: SECURE256:-VERS-SSL3.0
      LDAP_TLS_VERIFY_CLIENT: demand
      LDAP_REPLICATION: false
      KEEP_EXISTING_CONFIG: false
      LDAP_REMOVE_CONFIG_AFTER_SETUP: true
      LDAP_SSL_HELPER_PREFIX: ldap
      LDAP_PORT_1: 389
      LDAP_PORT_2: 636
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: false # https is between outside world and proxy server
      PHPLDAPADMIN_HTTP_PORT: 8081 # only describes outside port
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: ncdatabase
      MYSQL_USER: nextcloud
      VERSION_TAG: 29.0.4 # increase this only if run through the updater in the app don't version jump
      PUID: 33
      PGID: 33
      NC_PORT: 8080 # inside port of container must be 80
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: secret
      NEXTCLOUD_INIT_HTACCESS: true
      PHP_MEMORY_LIMIT: 4096
      REDIS_HOST: redis-cache
      REDIS_HOST_PASSWORD: secret
      REDIS_PORT: 6379
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
      POSTGRES_VERSION_TAG: 13
      PAPERLESS_PORT: 8000
      PAPERLESS_FQDN: https://paperless.yourlocalcloud.de
      PAPERLESS_REDIS: redis://default:secret@redis-cache:6379
      PAPERLESS_DBHOST: paperless-db
      PAPERLESS_SECRET_KEY: secret
      PAPERLESS_ADMIN_USER: admin
      PAPERLESS_ADMIN_PASSWORD: secret
      PAPERLESS_URL: https://paperless.yourlocalcloud.de
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_TIME_ZONE: Europe/Wien
      PAPERLESS_TASK_WORKERS: 4
      PAPERLESS_THREADS_PER_WORKER: 4
      PAPERLESS_CONSUMPTION_DIR: /usr/src/paperless/consume
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless-gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://paperless-tika:9998
      PAPERLESS_OCR_MAX_IMAGE_PIXELS: 1958594800
      PAPERLESS_PUID: 33
      PAPERLESS_PGID: 33 # collabora
      DOMAIN: nc.yourlocalcloud.de
      COLLABORA_USER: admin
      COLLABORA_PASSWORD: secret
      COLLABORA_HOST: collabora.yourlocalcloud.de
      COLLABORA_NETWORK: backbone
      COLLABORA_PORT: 9980
      COLLABORA_PROT: https

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update -y
          sudo apt-get install docker-compose -y

      - name: Validate docker-compose.yml
        run: docker-compose -f docker-compose.yaml config