name: Validate Docker Compose

on:
  pull_request:
    branches:
      - master

jobs:
  validate-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Validate docker-compose.yml
        run: docker-compose -f docker-compose.yml config